FROM docker.io/library/tomcat:9.0.88-jdk11

MAINTAINER "LEE JEONGHEON<colosair@gmail.com>"

RUN rm -rf /usr/local/tomcat/webapps/

EXPOSE 9999
ADD server.xml /usr/local/tomcat/conf/server.xml
ADD mysql-connector-j-8.0.33.jar /usr/local/tomcat/lib/
ADD target/cardgarden.war /usr/local/tomcat/webapps/cardgarden.war
